lib/awards_voter_web/router.ex
defmodule AwardsVoterWeb.Router do
  use AwardsVoterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AwardsVoterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AwardsVoterWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AwardsVoterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AwardsVoterWeb.Telemetry
    end
  end
end

lib/web/router.ex
defmodule AwardsVoter.Web.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AwardsVoter.Web.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", AwardsVoter.Web do
    pipe_through :browser

    get "/", AdminController, :admin_index
    get "/shows", AdminController, :list_shows
    get "/shows/:id", AdminController, :get_show
    live "/shows/:id/edit", AdminShowEdit
    delete "/shows/:id", AdminController, :delete_show
    post "/shows/json", AdminController, :upload_show_json
  end

  scope "/", AwardsVoter.Web do
    pipe_through :browser

    get "/", BallotController, :home
    get "/ballots/:id", BallotController, :get_ballot
    live "/ballots/:show_id/new", BallotNew
    live "/ballots/:id/edit", BallotEdit
    live "/ballots/:first_ballot/:second_ballot", BallotCompare
    live "/show/:id/scoreboard", Scoreboard
    live "/show/:id/summary", BallotsSummary
  end

  # Other scopes may use custom stacks.
  # scope "/api", AwardsVoter.Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AwardsVoter.Web.Telemetry
    end
  end
end

lib/web/live/summaries/ballots_scoreboard.ex
defmodule AwardsVoter.Web.Scoreboard do
  use AwardsVoter.Web, :live_view

  alias AwardsVoter.Context.Admin
  alias AwardsVoter.Context.Ballots
  alias AwardsVoter.Context.Models.Show

  @buffer_airdate_duration 60 * 10 # users can still enter their votes up to 10 minutes after the starting time of the show

  def render(assigns) do
    AwardsVoter.Web.SummariesView.render("scoreboard.html", assigns)
  end

  def mount(%{"id" => show_id}, _, socket) do
    AwardsVoter.Web.Endpoint.subscribe("show:#{show_id}")


    socket = assign_new(socket, :show, fn -> Admin.get_show_by_id(show_id) end)
    socket = assign_new(socket, :ballots, fn ->
        Ballots.fetch_ballots_for_show(show_id)
        |> Enum.sort_by(fn ballot -> {AwardsVoter.Web.SummariesView.num_correct(ballot, socket.assigns.show), AwardsVoter.Web.SummariesView.num_voted(ballot)} end, :desc)
      end)

    socket = assign(socket, :show_view_ballot, is_nil(socket.assigns.show.air_datetime) or !airtime_is_valid(socket.assigns.show))

    {:ok, socket}
  end

  def handle_params(params, _uri, socket) do
    current_ballot_id = Map.get(params, "current_ballot")
    socket = assign(socket, current_ballot_id: current_ballot_id)
    {:noreply, socket}
  end

  def handle_info(%Phoenix.Socket.Broadcast{event: "winner_updated", payload: _map_with_category_and_contestant, topic: "show:" <> show_id}, socket) do
    %Show{} = show = Admin.get_show_by_id(show_id)
    socket = assign(socket, :show, show)
    {:noreply, socket}
  end

  def handle_info(%Phoenix.Socket.Broadcast{event: "ballot_updated", payload: _map_with_updated_ballot, topic: "show:" <> show_id}, socket) do
    ballots =
      Ballots.fetch_ballots_for_show(show_id)
      |> Enum.sort_by(fn ballot -> {AwardsVoter.Web.SummariesView.num_correct(ballot, socket.assigns.show), AwardsVoter.Web.SummariesView.num_voted(ballot)} end, :desc)
    socket = assign(socket, :ballots, ballots)
    {:noreply, socket}
  end

  defp airtime_is_valid(%Show{air_datetime: air_datetime}) do
    {:ok, datetime, _utc_offset} = DateTime.from_iso8601(air_datetime <> ":00Z")
    {:ok, datetime_est} = DateTime.from_naive(datetime, "America/Toronto", Tz.TimeZoneDatabase)
    {:ok, now} = DateTime.now("America/Toronto", Tz.TimeZoneDatabase)
    DateTime.diff(now, datetime_est) <= @buffer_airdate_duration
  end
end

lib/web/live/summaries/ballots_summary.ex
defmodule AwardsVoter.Web.BallotsSummary do
  use AwardsVoter.Web, :live_view

  alias AwardsVoter.Context.Admin
  alias AwardsVoter.Context.Ballots
  alias AwardsVoter.Context.Models.Show

  def render(assigns) do
    AwardsVoter.Web.SummariesView.render("ballots_summary.html", assigns)
  end

  def mount(%{"id" => show_id}, _, socket) do
    AwardsVoter.Web.Endpoint.subscribe("show:#{show_id}")

    socket =
      socket
      |> assign_new(:show, fn -> Admin.get_show_by_id(show_id) end)
      |> assign_new(:ballots, fn -> Ballots.fetch_ballots_for_show(show_id) end)

    {:ok, socket}
  end

  def handle_params(params, _uri, socket) do
    current_ballot_id = Map.get(params, "current_ballot")
    socket = assign(socket, current_ballot_id: current_ballot_id)
    {:noreply, socket}
  end

  def handle_info(%Phoenix.Socket.Broadcast{event: "winner_updated", payload: _map_with_category_and_contestant, topic: "show:" <> show_id}, socket) do
    %Show{} = show = Admin.get_show_by_id(show_id)
    socket = assign(socket, :show, show)
    {:noreply, socket}
  end

  def handle_info(%Phoenix.Socket.Broadcast{event: "ballot_updated", payload: _map_with_updated_ballot, topic: "show:" <> show_id}, socket) do
    ballots = Ballots.fetch_ballots_for_show(show_id)
    socket = assign(socket, :ballots, ballots)
    {:noreply, socket}
  end
end

lib/web/views/summaries_view.ex
defmodule AwardsVoter.Web.SummariesView do
  use AwardsVoter.Web, :view

  alias AwardsVoter.Context.Models.Ballot
  alias AwardsVoter.Context.Models.Vote
  alias AwardsVoter.Context.Models.Category
  alias AwardsVoter.Context.Models.Show

  def num_voted(%Ballot{votes: votes}) do
    Enum.count(votes, fn vote -> !is_nil(vote.contestant) end)
  end

  def percent_correct_by_voted(ballot, show) do
    num_voted = num_voted(ballot)
    num_correct = num_correct(ballot, show)
    if num_voted == 0 or num_correct == 0 do
      "0.00" |> String.to_float()
    else
      Kernel./(num_correct, num_voted) |> Kernel.*(100) |> Float.round(1)
    end
  end

  def percent_correct_by_categories(ballot, show) do
    num_winners = num_winners(show)
    num_correct = num_correct(ballot, show)

    if num_winners == 0 or num_correct == 0 do
      "0.00" |> String.to_float()
    else
      Kernel./(num_correct, num_winners) |> Kernel.*(100)  |> Float.round(1)
    end
  end

  def num_winners(%Show{} = show) do
    Enum.count(winning_categories(show, []))
  end

  def num_categories(%Show{categories: categories}), do: Enum.count(categories)

  def winning_categories(%Show{categories: categories}, ballots) do
    categories
    |> Enum.filter(fn category -> !is_nil(category.winner) end)
    |> Enum.sort_by(fn category -> num_correct_voted_for_category(category, ballots) end, :desc)
  end

  def num_correct_voted_for_category(category, ballots) do
    Enum.count(ballots, fn %Ballot{votes: votes} ->
      case Enum.find(votes, fn vote -> vote.category.name == category.name end) do
        %Vote{contestant: contestant} -> contestant.name == category.winner.name
        _ -> false
      end
    end)
  end

  def percent_correct_voted_for_category(_show, category, ballots) do
    num_ballots_with_vote_for_category = Enum.count(ballots, fn %Ballot{votes: votes} -> Enum.find(votes, fn vote -> vote.category.name == category.name end) end)
    num_ballots_with_correct_votes = num_correct_voted_for_category(category, ballots)

    if num_ballots_with_vote_for_category == 0 or num_ballots_with_correct_votes == 0 do
      "0.00" |> String.to_float()
    else
      Kernel./(num_ballots_with_correct_votes, num_ballots_with_vote_for_category) |> Kernel.*(100)  |> Float.round(1)
    end
  end

  def most_common_vote(%Category{name: category_name}, ballots) do
    Enum.frequencies_by(ballots, fn %Ballot{votes: votes} ->
      case Enum.find(votes, fn vote -> vote.category.name == category_name end) do
        %Vote{contestant: contestant} -> contestant.name
        _ -> :not_vote
      end
    end)
    |> Map.drop([:not_vote])
    |> Enum.max_by(fn {_, num_votes} -> num_votes end, &>=/2, fn -> {nil, nil} end)
  end

  def num_correct(ballot, %Show{categories: categories}) do
    Enum.count(ballot.votes, fn
      %Vote{category: category, contestant: contestant} ->
        cat = Enum.find(categories, fn show_category -> show_category.name == category.name end)
        contestant.name == Map.get(cat.winner || %{}, :name)
      _ -> false
    end)
  end

end

lib/web/templates/summaries/ballots_summary.html.leex
<div class="prose mx-auto lg:my-4 my-12 px-4">
    <h1>Summary of ballots cast for <%= @show.name %></h1>
</div>
<section class="p-0 md:p-10">
    <div class="bg-white p-0 pt-4 md:p-4 overflow-x-auto">
        <div class="flex flex-col md:flex-row justify-between">
            <%= live_redirect "See live scoreboard for this show", to: Routes.live_path(@socket,  AwardsVoter.Web.Scoreboard, @show.id, current_ballot: @current_ballot_id), class: "font-bold text-yellow-400 hover:text-yellow-600" %>
            <p><strong><%= num_winners(@show) %> / <%= num_categories(@show) %></strong> categories have been updated with winners</p>
        </div>

        <table class="min-w-full table-auto mt-4">
            <thead class="justify-between">
                <tr>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-left">Category</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-left">Winner</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">Number of correctly cast votes</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">% of votes correctly cast</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">Most commonly cast vote</th>
                </tr>
            </thead>

            <tbody class="bg-gray-200">
                <%= if Enum.empty? winning_categories(@show, @ballots) do %>
                    <tr class="bg-white border-b-2 border-l-2 border-r-2 border-gray-200">
                        <td colspan="5" class="p-4">No winners have been selected yet for this show.</td>
                    </tr>
                <% else %>
                    <%= for category <- winning_categories(@show, @ballots) do %>
                    <tr class="bg-white border-b-2 border-gray-200">
                        <td class="p-4 text-left"><%= category.name %></td>
                        <td class="p-4 text-left"><%= category.winner.name %></td>
                        <td class="p-4 text-right"><%= num_correct_voted_for_category(category, @ballots) %></td>
                        <td class="p-4 text-right"><%= percent_correct_voted_for_category(@show, category, @ballots) %></td>
                        <td class="p-4 text-right">
                            <%= case most_common_vote(category, @ballots) do %>
                            <% {nil, nil} -> %> <span></span>
                            <% {name, vote_count} -> %> <%= name %> (<%= vote_count %>)
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

lib/web/templates/summaries/scoreboard.html.leex
<div class="prose mx-auto lg:my-4 my-12 px-4">
    <h1>Scoreboard for <%= @show.name %></h1>
</div>
<section class="p-0 md:p-10">
    <div class="bg-white p-0 pt-4 md:p-4 overflow-x-auto">
        <div class="flex flex-col md:flex-row justify-between">
            <%= live_redirect "See ballot summary for this show", to: Routes.live_path(@socket,  AwardsVoter.Web.BallotsSummary, @show.id, current_ballot: @current_ballot_id), class: "font-bold text-yellow-400 hover:text-yellow-600" %>
            <p><strong><%= num_winners(@show) %> / <%= num_categories(@show) %></strong> categories have been updated with winners</p>
        </div>

        <table class="min-w-full table-auto mt-4">
            <thead class="justify-between">
                <tr>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-left">Ballot name</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">Number of votes cast</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">Number of correct votes</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">% Correct votes (of cast votes)</th>
                    <th class="bg-yellow-500 bg-opacity-90 p-4 text-right">% Correct votes (of updated categories)</th>
                    <%= if @show_view_ballot do %>
                        <th class="bg-yellow-500 bg-opacity-90 p-4"></th>
                    <% end %>
                </tr>
            </thead>

            <tbody class="bg-gray-200">
                <%= for ballot <- @ballots do %>
                 <tr class="bg-white border-b-2 border-gray-200">
                     <td class="p-4"><%= ballot.ballot_name %></td>
                     <td class="p-4 text-right"><%= num_voted(ballot) %></td>
                     <td class="p-4 text-right"><%= num_correct(ballot, @show) %></td>
                     <td class="p-4 text-right"><%= percent_correct_by_voted(ballot, @show) %></td>
                     <td class="p-4 text-right"><%= percent_correct_by_categories(ballot, @show) %></td>
                     <%= if @show_view_ballot do %>
                        <td class="p-4 text-center">
                            <%= if is_nil(@current_ballot_id) do %>
                                <%= link "View this ballot", to: Routes.ballot_path(@socket, :get_ballot, ballot.id, read_only: true), class: "font-bold text-yellow-400 hover:text-yellow-600" %>
                            <% else %>
                                <%= if ballot.id == @current_ballot_id do %>
                                    <%= link "View my ballot", to: Routes.ballot_path(@socket, :get_ballot, ballot.id), class: "font-bold text-yellow-400 hover:text-yellow-600" %>
                                <% else %>
                                    <%= link "Compare with this ballot", to: Routes.live_path(@socket, AwardsVoter.Web.BallotCompare, @current_ballot_id, ballot.id), class: "font-bold text-yellow-400 hover:text-yellow-600" %>
                                <% end %>
                            <% end %>
                        </td>
                     <% end %>
                 </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>